# Site settings
baseURL = "https://hackingstuff.xyz/"
title = "hackingstuff.xyz"
theme = "hello-friend-ng"
enableRobotsTXT = true
defaultContentLanguage = "en"

# Parameters
[params]
  homeSubtitle = "A CTF writeup repository by Hugo Barea"
  enableGlobalLanguageMenu = false   # disable language menu
  enableSharingButtons = true

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/hugo-barea/"

  [[params.social]]
    name = "twitter"
    url = "https://x.com/hugobarea_"

  [[params.social]]
    name = "hackthebox"
    url = "https://app.hackthebox.com/profile/overview"

# Menus
[[menu.main]]
  identifier = "writeups"
  name = "Writeups"
  url = "/writeups/"
  weight = 1

[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 2

[[menu.main]]
  parent = "writeups"
  name = "TryHackMe"
  url = "/writeups/tryhackme/"
  weight = 3

[[menu.main]]
  parent = "writeups"
  name = "HackTheBox"
  url = "/writeups/hackthebox/"
  weight = 4

# Taxonomies
[taxonomies]
  tag = "tags"
  difficulty = "difficulties"

# Sitemap settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
