defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = 'hackingstuff.xyz'
theme = 'hello-friend-ng'
baseURL = 'https://hackingstuff.xyz/'

[params]
  homeSubtitle = "A CTF writeup repository"
  enableGlobalLanguageMenu = true
  enableSharingButtons = true

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/hugo-barea/"

[[params.social]]
  name = "twitter"
  url = "https://x.com/hugobarea_"

[[params.social]]
  name = "hackthebox"
  url = "https://app.hackthebox.com/profile/overview"

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    baseURL = 'https://hackingstuff.xyz/'

    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A CTF writeup repository"

    [languages.en.params.logo]
      logoText = "hackingstuff.xyz"
      logoHomeLink = "/"
  
  [languages.es]
    disabled = false
    languageCode = 'es-ES'
    languageName = 'Español'
    keywords = ""
    baseURL = 'https://hackingstuff.xyz/es'
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.es.params]
    subtitle  = "Un repositorio de writeups de CTFs"

    [languages.es.params.logo]
      logoText = "hackingstuff.xyz"
      logoHomeLink = "/es"